### ISSUE TITLE
wrong path for libplywood_Instantiators.dylib on macos

### ISSUE THREAD

**Issue by sherjilozair** [arc80/plywood#1]
```
% plytool target add test
Initializing repo registry...
Error loading '/Users/sherjilozair/plywood/data/build/bootstrap/DLLs/build/Debug/libplywood_Instantiators.dylib':
dlopen(/Users/sherjilozair/plywood/data/build/bootstrap/DLLs/build/Debug/libplywood_Instantiators.dylib, 1): image not found
```

I get the above error. The dylib is present in the parent directory though: `/Users/sherjilozair/plywood/data/build/bootstrap/DLLs/build/libplywood_Instantiators.dylib`

**Comment by preshing** [comment]
Hello and thanks for reporting this. I also heard about this bug yesterday in the Discord chat.

This bug occurs when you [initialize the workspace](https://plywood.arc80.com/docs/QuickStart) on macOS using `-DPRESET=make` due to bad logic in [BuildInstantiatorDLLs.cpp](https://github.com/arc80/plywood/blob/master/repos/plywood/src/build/repo/ply-build-repo/BuildInstantiatorDLLs.cpp#L168). As a workaround, you can either:

1. re-init the workspace using `-DPRESET=xcode` making sure you have the latest changes; or
2. remove the `cmakeOptions.buildType` argument on [line 169](https://github.com/arc80/plywood/blob/master/repos/plywood/src/build/repo/ply-build-repo/BuildInstantiatorDLLs.cpp#L169) of that file.

I'll work on a better fix. This issue is related to something else I'd like to add: a `plytool run` command that knows where the target executables are in every type of build folder.

**Comment by preshing** [comment]
I added a function [getTargetOutputPath()](https://github.com/arc80/plywood/blob/1eae44d8bef4dfe399ca35b1150786eb954c0e43/repos/plywood/src/build/target/ply-build-target/CMakeLists.cpp#L287) with better logic for determining the output location of build targets. The issue should now be fixed.

**Comment by sherjilozair** [comment]
Yes it is. Thanks!
