### ISSUE TITLE
Errors when building plywood

### ISSUE THREAD

**Issue by mingodad** [arc80/plywood#11]
I noticed that when building the `plywood` tool I'm getting several errors like:
```
[100%] Built target plytool
Initializing repo registry...
Generating code using PlyTool...
plywood/repos/plywood/src/math/tests/TestFloat2.cpp(12, 15): error: expected ')' before '"Float2 constructors"'
plywood/repos/plywood/src/math/tests/TestFloat2.cpp(12, 38): error: expected declaration before '{'
plywood/repos/plywood/src/math/tests/TestFloat2.cpp(21, 15): error: expected ')' before '"Float2 conversions"'
plywood/repos/plywood/src/math/tests/TestFloat2.cpp(21, 37): error: expected declaration before '{'
```

**Comment by preshing** [comment]
Thanks for reporting this. I broke it in a recent change because I don't have a very good test process yet. The problem is that my C++ parser (which is used during the code generation step) doesn't handle preprocessor macros very well. I'll submit a fix to make this folder opt out of code generation. A better fix will be to make code generation opt-in instead of opt-out...
