### ISSUE TITLE
StringMixin<Derived>::rfindByte(const MatchFuncOrChar& matchFuncOrByte) compile error

### ISSUE THREAD

**Issue by kidnewthe** [arc80/plywood#22]
When I use this function like

```
String buf = "balbalbalbal";
auto chartest = [](const char p) {
    if (p == 'a')
         return true;
    return false;
};
auto has = buf.rfindByte(chartest);
```

compile error here "'numBytes': is not a member of 'ply::StringMixin<ply::String>'"

this can fix error
```    
PLY_INLINE s32 rfindByte(const MatchFuncOrChar& matchFuncOrByte) const {
        return static_cast<const Derived*>(this)->view().rfindByte(
            matchFuncOrByte, static_cast<const Derived*>(this)->numBytes - 1);
    }
```
by the way,this function no 
**s32 rfindByte(char matchByte) const**
version

**Comment by preshing** [comment]
Thanks for reporting this. Fix has been submit.

> by the way,this function no **s32 rfindByte(char matchByte) const** version

It's been a little while since I wrote this code but I don't think there's a need for such an explicit `rfindByte` overload in the `StringMixin` class template because `str.rfindByte('c')` already compiles fine. It's handled by the function template [here](https://github.com/arc80/plywood/blob/b24a5e76bafb1e5e675d2269d6f4e135fadb3d9b/repos/plywood/src/runtime/ply-runtime/string/StringMixin.h#L131).
